---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: src/galerie
  label: Photos
  create: documents
  match: "**/*"
  templates:
  - photo
- type: directory
  path: src/prestations
  label: Prestations
  create: documents
  match: "**/*"
  templates:
  - prestation
upload_dir: src/img/galerie
public_path: "/src/img/galerie"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
